//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEmailSignatures.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class SignatureHtml
    {
        public int HTMLID { get; set; }
        [UIHint("tinymce_jquery_full"), AllowHtml]
        public string htmlString { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public string AOF { get; set; }
    }
}
