//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEmailSignatures.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffList
    {
        public int StaffID { get; set; }
        public string Name { get; set; }
        public string title { get; set; }
        public string department { get; set; }
        public string workemail { get; set; }
        public string workphone { get; set; }
        public string AOF { get; set; }
    }
}
